### ISSUE TITLE
Expose newAdapter func

### ISSUE THREAD

**Issue by emicklei** [traefik-contrib/yaegi-debug-adapter#3]
hi,

I am developing a Go debugger on top of this package.
For that, I need to create an Adaptor using a different compile function.
Currently, the `newAdapter` constructor function is private.

My proposal is to either expose it or add another function that allows this use case, such as:

```golang
// NewAdapter returns a new Adapter that debugs Go code located at the
// given path and compiles it with a given Interpreter compile function.
func NewAdapter(path string, eval compileFunc, opts *Options) *Adapter {
	return newAdapter(eval, path, opts)
}
```

**Comment by ldez** [comment]
I think you can expose the `newAdapter` function.

**Comment by firelizzard18** [comment]
Sounds fine to me

**Comment by emicklei** [comment]
@firelizzard18 @ldez great, do you want me to create a PR?
