### ISSUE TITLE
More verbose debug variable values

### ISSUE THREAD

**Issue by emicklei** [traefik-contrib/yaegi-debug-adapter#6]
Hi,

I am working on a debugger on top of this package. 
For that I have extended the behaviour of `newVar` to have better visibility of the actual values.
```
func (a *Adapter) newVar(name string, rv reflect.Value) *dap.Variable
```
<img width="1359" alt="Screenshot 2024-06-04 at 17 32 13" src="https://github.com/traefik-contrib/yaegi-debug-adapter/assets/686220/06e4e94c-b7ac-4b05-ba80-cc8626bf412f">

(this is screenshot from Visual Studio Code working with my debugger.

The changes are here:
https://github.com/emicklei/yaegi-debug-adapter/blob/89cbdd701673086c0200b5aa7e7cf431b376a122/variables.go#L86

I am happy submit a PR but would like to have feedback on the idea and approach before doing so.

**Comment by firelizzard18** [comment]
At a glance from the diff https://github.com/traefik-contrib/yaegi-debug-adapter/compare/main...emicklei:yaegi-debug-adapter:feature/more-newVar-cases it looks like a reasonable approach. Please open a PR and I'll look at it more in-depth there.
